### ISSUE TITLE
print stylesheet

### ISSUE THREAD

**Issue by npdoty** [privacypatterns/privacypatterns#89]
Current stylesheet removes all margins by default, which makes for a messy job when printing a pattern out onto paper. It would be nice to have a separate stylesheet or a media-query section that provides an appropriate layout for printing.

**Comment by p4pnl** [comment]
Perhaps this:
```css
    /* For printing, removes margin and contents, separates patterns into further pages */
    @media print{
      body{
        margin: 0px;
      }
      #content {
        display: block;
        width: 100%;
      }
    }
```
